version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Hiero"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels: ["dependencies", "nuget"]
    ignore:
      - dependency-name: "*"
        versions: ["*-alpha*", "*-beta*", "*-rc*"]
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:10"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels: ["dependencies", "github-actions"]
