namespace Hiero;

/// <summary>
/// Represents an unexpected termination or exception received
/// from a mirror stream.
/// </summary>
public sealed class MirrorGrpcException : Exception
{
    /// <summary>
    /// The status code identifying the error condition.
    /// </summary>
    public MirrorGrpcExceptionCode Code { get; private set; }
    /// <summary>
    /// Public Constructor.
    /// </summary>
    /// <param name="message">
    /// The message generated by the library describing the 
    /// condition that raised the exception.
    /// </param>
    public MirrorGrpcException(string? message, MirrorGrpcExceptionCode code, Exception? innerException) : base(message, innerException)
    {
        Code = code;
    }
}