using System;
using System.Net;

namespace Hiero.Mirror;
/// <summary>
/// Exception raised when a mirror request or simulated evm call has failed.
/// </summary>
public class MirrorException : Exception
{
    /// <summary>
    /// The http status code returned from the mirror node request.
    /// </summary>
    public HttpStatusCode StatusCode { get; private set; }
    /// <summary>
    /// The detailed error details returned by the mirror node.
    /// </summary>
    public MirrorError[] Details { get; private set; }
    /// <summary>
    /// Public Constructor.
    /// </summary>
    /// <param name="message">
    /// The message generated by the library describing the 
    /// condition that raised the exception.
    /// </param>
    public MirrorException(string message, MirrorError[] details, HttpStatusCode code) : base(message)
    {
        StatusCode = code;
        Details = details;
    }
}