// SPDX-License-Identifier: Apache-2.0
using Google.Protobuf;
using Proto;
using System.Runtime.InteropServices;

namespace Hiero.Implementation;

internal sealed class Invoice : IInvoice
{
    private readonly TransactionId _transactionId;
    private readonly string _memo;
    private readonly ReadOnlyMemory<byte> _txBytes;
    private readonly int _prefixTrimLimit;
    private readonly Dictionary<ByteString, SignaturePair> _signatures;
    private readonly CancellationToken _cancellationToken;

    TransactionId IInvoice.TransactionId => _transactionId;
    string IInvoice.Memo => _memo;
    ReadOnlyMemory<byte> IInvoice.TransactionBytes => _txBytes;
    int IInvoice.MinimumDesiredPrefixSize => _prefixTrimLimit;
    CancellationToken IInvoice.CancellationToken => _cancellationToken;

    internal Invoice(TransactionBody transactionBody, int prefixTrimLimit, CancellationToken cancellationToken)
    {
        _transactionId = transactionBody.TransactionID.AsTransactionId();
        _memo = transactionBody.Memo;
        _txBytes = transactionBody.ToByteArray();
        _prefixTrimLimit = prefixTrimLimit;
        _cancellationToken = cancellationToken;
        _signatures = [];
    }
    internal Invoice(ReadOnlyMemory<byte> transactionBodyBytes, int prefixTrimLimit, CancellationToken cancellationToken)
    {
        var transactionBody = TransactionBody.Parser.ParseFrom(transactionBodyBytes.Span);
        _transactionId = transactionBody.TransactionID.AsTransactionId();
        _memo = transactionBody.Memo;
        _txBytes = transactionBodyBytes;
        _prefixTrimLimit = prefixTrimLimit;
        _signatures = [];
    }
    void IInvoice.AddSignature(KeyType type, ReadOnlySpan<byte> publicPrefix, ReadOnlySpan<byte> signature)
    {
        var key = ByteString.CopyFrom(publicPrefix);
        var value = ByteString.CopyFrom(signature);
        var pair = new SignaturePair();
        switch (type)
        {
            case KeyType.Ed25519:
                pair.Ed25519 = value;
                break;
            case KeyType.ECDSASecp256K1:
                pair.ECDSASecp256K1 = value;
                break;
            case KeyType.Contract:
                pair.Contract = value;
                break;
        }
        ref var existing = ref CollectionsMarshal.GetValueRefOrAddDefault(_signatures, key, out var exists);
        if (exists)
        {
            if (!pair.Equals(existing))
            {
                throw new ArgumentException("Signature with Duplicate Prefix Identifier was provided, but did not have an Identical Signature.");
            }
        }
        else
        {
            existing = pair;
        }
    }
    internal SignedTransaction GenerateSignedTransactionFromSignatures(bool failIfNoSignatures)
    {
        var sigMap = TryGenerateMapFromCollectedSignatures();
        if (sigMap is null && failIfNoSignatures)
        {
            throw new InvalidOperationException("A transaction or query requires at least one signature, sometimes more.  None were generated by the provided signatories, did you forget to assign a non-scheduling Signatory to the context, transaction or query?");
        }
        return new SignedTransaction
        {
            BodyBytes = ByteString.CopyFrom(_txBytes.Span),
            SigMap = sigMap
        };
    }
    internal SignatureMap? TryGenerateMapFromCollectedSignatures()
    {
        var count = _signatures.Count;
        if (count == 0)
        {
            return null;
        }
        var map = new SignatureMap();
        if (count == 1 && _prefixTrimLimit < 1)
        {
            foreach (var signature in _signatures.Values)
            {
                map.SigPair.Add(signature);
                return map;
            }
        }
        else
        {
            var prefixLength = FindUniquePrefixLength(_signatures, _prefixTrimLimit);
            foreach (var entry in _signatures)
            {
                var key = entry.Key;
                var sig = entry.Value;
                var length = Math.Min(key.Length, prefixLength);
                sig.PubKeyPrefix = ByteString.CopyFrom(key.Span.Slice(0, length));
                map.SigPair.Add(sig);
            }
        }
        return map;

        static int FindUniquePrefixLength(Dictionary<ByteString, SignaturePair> signatures, int prefixTrimLimit)
        {
            var prefixLength = Math.Max(1, prefixTrimLimit);
            var firstIndex = 0;
            foreach (var first in signatures.Keys)
            {
                var secondIndex = 0;
                foreach (var second in signatures.Keys)
                {
                    if (secondIndex++ > firstIndex)
                    {
                        prefixLength = Math.Max(prefixLength, CommonPrefixLength(first.Span, second.Span) + 1);
                    }
                }
                firstIndex++;
            }
            return prefixLength;
        }

        static int CommonPrefixLength(ReadOnlySpan<byte> first, ReadOnlySpan<byte> second)
        {
            var length = Math.Min(first.Length, second.Length);
            for (var i = 0; i < length; i++)
            {
                if (first[i] != second[i])
                {
                    return i;
                }
            }
            return length;
        }
    }
}
