// SPDX-License-Identifier: Apache-2.0
namespace Hiero;
/// <summary>
/// Represents an error with a contract query that passed the gateway node
/// pre-check and was processed by the gossip node but did not succeed. It
/// includes additional information returned by the hedera contract
/// virtual machine. Transaction fees will have been spent.
/// </summary>
/// <remarks>
/// <para>
/// Contract exceptions are <strong>generally permanent</strong> — they
/// represent EVM-level failures (revert, out-of-gas, invalid opcode) that
/// will produce the same result if retried with identical inputs.
/// </para>
/// <para>
/// Inspect <see cref="CallResult"/> for EVM-level details: the revert
/// reason string (if the contract emitted one), gas consumption, and any
/// events that fired before the revert. The <see cref="Status"/> property
/// carries the Hedera-level response code
/// (e.g. <see cref="ResponseCode.ContractRevertExecuted"/>).
/// </para>
/// <para>
/// For <see cref="ResponseCode.InsufficientGas"/>, increase the
/// <c>Gas</c> property on your <see cref="CallContractParams"/> or
/// <see cref="QueryContractParams"/> and retry. For other codes, review
/// the contract's Solidity logic and the inputs that caused the revert.
/// </para>
/// <para>
/// When using <see cref="QueryContractParams"/>, you can suppress this
/// exception by setting <see cref="QueryContractParams.ThrowOnFail"/> to
/// <c>false</c> — the <see cref="ContractCallResult"/> is then returned
/// directly so you can inspect the failure without a try/catch.
/// </para>
/// </remarks>
public sealed class ContractException : Exception
{
    /// <summary>
    /// The <see cref="ResponseCode"/> returned by the network
    /// prior to transaction request expiration.
    /// </summary>
    public ResponseCode Status { get; private set; }
    /// <summary>
    /// The TransactionId ID generated by the library (or client code) 
    /// identifying the request.
    /// </summary>
    public TransactionId TransactionId { get; private set; }
    /// <summary>
    /// If the returned status is <see cref="ResponseCode.InsufficientTxFee"/>
    /// this value will contain the transaction fee necessary to execute the transaction.
    /// </summary>
    public ulong RequiredFee { get; private set; }
    /// <summary>
    /// The results returned from the failed call to the 
    /// smart contract virtual machine.
    /// </summary>
    public ContractCallResult CallResult { get; private set; }
    /// <summary>
    /// Internal Constructor.
    /// </summary>
    /// <param name="message">
    /// The message generated by the library describing the 
    /// condition that raised the exception.
    /// </param>
    /// <param name="transaction">
    /// The TransactionId ID of the request that failed.
    /// </param>
    /// <param name="code">
    /// The final <see cref="ResponseCode"/> returned by the network 
    /// prior to transaction request expiration.
    /// </param>
    /// <param name="cost">
    /// The fee cost associated with the failed transaction.
    /// </param>
    /// <param name="callResult">
    /// The results returned from the contract, which may include
    /// additional information regarding the error.
    /// </param>
    internal ContractException(string message, TransactionId transaction, ResponseCode code, ulong cost, ContractCallResult callResult) : base(message)
    {
        Status = code;
        TransactionId = transaction;
        RequiredFee = cost;
        CallResult = callResult;
    }
}